### ISSUE TITLE
Regarding step finder failing issue

### ISSUE THREAD

**Issue by Swathi1794** [tobiasjj/stepfinder#1]
Hello Tobi,
When I tried to import modules, i got an error Building module stepfinder.fast failed. Herewith I have also attached the file. 
![image](https://user-images.githubusercontent.com/81228571/112296305-ad8de600-8c8c-11eb-93eb-8bd78713bd66.png)

Thanks for helping

**Comment by tobiasjj** [comment]
I modified the stepfinder package to be able to run on Windows and fixed the automatic build process. Please, use the latest version (65c8a6a).

Please, let me know if this solved your issue.

If the automatic compilation of `fast.pyx` still fails on Windows, you could try to manually provide the stepfinder with the compilation library `fast.pyd`. If you have a recent Anaconda installation with Python version 3.8, you could try to [download the zipped library fast.zip](https://github.com/tobiasjj/stepfinder/files/6200610/fast.zip) to the subfolder stepfinder (next to the `fast.pyx` file) and extract the library `fast.pyd`.

If the example code still does not run, you would have to compile the library yourself:
1. Open an "Anaconda Prompt", change into the stepfinder folder and convert thy `fast.pyx` file into a C source file: `cython fast.pyx`
2. Open a "x64 Native Tools Command Prompt" for Visual Studio, change into the stepfinder folder and compile the library with the command:
   `cl /LD /I[directory with Python.h] \I[directory with numpy header files] `fast.c` [the python3X.lib file]`
  for me this was:
  `cl /LD /IC:\ProgramData\Anaconda3\include /IC:\ProgramData\Anaconda3\lib\site-packages\numpy\core\include fast.c C:\ProgramData\Anaconda3\libs\python38.lib`
3. Rename the file `fast.dll` to `fast.pyd`: `move fast.dll fast.pyd`

**Comment by Swathi1794** [comment]
Thanks a lot Tobi,
It worked well now.

Thanks again
