### ISSUE TITLE
installing/runnning on Mac

### ISSUE THREAD

**Issue by ecutts** [tobiasjj/stepfinder#4]
Hello,

I'm trying to get this working on a Mac and the installation is failing with the following error

> _pip install git+git://github.com/tobiasjj/stepfinder.git
> Collecting git+git://github.com/tobiasjj/stepfinder.git
>   Cloning git://github.com/tobiasjj/stepfinder.git to /private/var/folders/s9/0gg3gyn17c12fxfxckn9vsrm0000gq/T/pip-req-build-nncknyp_
>   Running command git clone -q git://github.com/tobiasjj/stepfinder.git /private/var/folders/s9/0gg3gyn17c12fxfxckn9vsrm0000gq/T/pip-req-build-nncknyp_
>     ERROR: Command errored out with exit status 1:
>      command: /Users/ecutts/opt/anaconda3/envs/step/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/s9/0gg3gyn17c12fxfxckn9vsrm0000gq/T/pip-req-build-nncknyp_/setup.py'"'"'; __file__='"'"'/private/var/folders/s9/0gg3gyn17c12fxfxckn9vsrm0000gq/T/pip-req-build-nncknyp_/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/s9/0gg3gyn17c12fxfxckn9vsrm0000gq/T/pip-pip-egg-info-zailn9u1
>          cwd: /private/var/folders/s9/0gg3gyn17c12fxfxckn9vsrm0000gq/T/pip-req-build-nncknyp_/
>     Complete output (5 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/Users/ecutts/opt/anaconda3/envs/step/lib/python3.9/tokenize.py", line 392, in open
>         buffer = _builtin_open(filename, 'rb')
>     FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/s9/0gg3gyn17c12fxfxckn9vsrm0000gq/T/pip-req-build-nncknyp_/setup.py'
>     ----------------------------------------
> WARNING: Discarding git+git://github.com/tobiasjj/stepfinder.git. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.__
> 

If I try to run the stepfinder.py directly, it looks like it is failing to import from the .fast: 

> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> <ipython-input-1-12a2f0ae2fb2> in <module>
>      23 from collections import namedtuple
>      24 
> ---> 25 from .fast import _iterative_variance
>      26 from .fast import _delete_close_center
>      27 from .fast import _calculate_plateau_heights
> 
> ImportError: attempted relative import with no known parent package_

I'm pretty new to coding, so if there is a non-standard install process I need to follow, let me know.
Best wishes,
Erin

**Comment by tobiasjj** [comment]
I haven't bothered to create a `setup.py` file (so far), which is why pip fails.
To install the stepfinder package you have to copy the whole package subfolder ["stepfinder"](https://github.com/tobiasjj/stepfinder/tree/master/stepfinder) and import the package (_not_ the module `stepfinder.py` within the folder itself).
Have a look in the [example notebook](https://github.com/tobiasjj/stepfinder/blob/master/notebooks/stepfinder.ipynb), where the stepfinder package is imported relative to the `notebooks` folder:
```
import sys
sys.path.append('..')
import stepfinder as sf
```

Upon import the fast.pyx file should be compiled automatically. However, I haven't tested the stepfinder package on a Mac, so I would appreciate if you let me know if this worked for you.
